services:
  dababase:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env
    container_name: dababase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
